{% set name = "helm-docs" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/norwoodj/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 628f1f9dac58eebba1f960863cdbf8045c9ec8fa740e32c7c15ac5edbf9963eb
    folder: src

build:
  number: 0
  script:
    - cd src
    - go install -v -ldflags "-X main.version={{ version }}" ./cmd/helm-docs
    - go-licenses save ./cmd/helm-docs --save_path ../library_licenses

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - helm-docs --version
    - helm-docs --help

about:
  home: https://github.com/norwoodj/helm-docs
  license: GPL-3.0-only
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: A tool for automatically generating markdown documentation for helm charts

extra:
  recipe-maintainers:
    - "0xbe7a"
